/*
 * LCD.c
 *
 *  Created on: Jul 11, 2020
 *      Author: Dell PC
 */
#include "../include.h"
#include "LCD.h"

//XXXXXXXXXXXXXXXXXXXXXXX XUAT GIA TRI CAN TRUYEN RA PORT XXXXXXXXXXXXXXXXXXXXXXXXXX
void OUTPUT_LCD(unsigned char MDK)
{
	int i;
	int j=1;
	for (i = 0; i < 8; i++) {
		GPIOPinWrite(LCD_DATA_PORT, j, ((MDK >> i) & 0x01)*j);
		j = j*2;
	  }
}

//XXXXXXXXXXXXXXXXXXXX TRUYEN VI TRI CAN HIEN THI TREN LCD XXXXXXXXXXXXXXXXXXXXXXXXX
void LCD_COMMAND(unsigned char MDK)
{
	GPIOPinWrite(LCD_CONTROL_PORT, LCD_RS, 0);
	OUTPUT_LCD(MDK);
	GPIOPinWrite(LCD_CONTROL_PORT, LCD_E, LCD_E);
	SysCtlDelay(SysCtlClockGet()/30000);
	GPIOPinWrite(LCD_CONTROL_PORT, LCD_E, 0);
	SysCtlDelay(SysCtlClockGet()/30000);
}

//XXXXXXXXXXXXXXXXXXXXXX TRUYEN DU LIEU CAN HIEN THI RA LCD XXXXXXXXXXXXXXXXXXXXXX
void LCD_DATA(unsigned char MHT)
{
	GPIOPinWrite(LCD_CONTROL_PORT, LCD_RS, LCD_RS);
	OUTPUT_LCD(MHT);
	GPIOPinWrite(LCD_CONTROL_PORT, LCD_E, LCD_E);
	SysCtlDelay(SysCtlClockGet()/30000);
	GPIOPinWrite(LCD_CONTROL_PORT, LCD_E, 0);
	SysCtlDelay(SysCtlClockGet()/30000);
}

//XXXXXXXXXXXXXXXXXXXXXXX CAI DAT LCD KHI KHOI TAO XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
void LCD_SETUP()
{
	SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
	SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOB);
	GPIOPinTypeGPIOOutput(GPIO_PORTA_BASE,LCD_RS|LCD_E|LCD_RW);
	GPIOPinTypeGPIOOutput(GPIO_PORTB_BASE,GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6|GPIO_PIN_7);
	GPIOPinWrite(LCD_CONTROL_PORT, LCD_E, 0);
	GPIOPinWrite(LCD_CONTROL_PORT, LCD_RS, 0);
	GPIOPinWrite(LCD_CONTROL_PORT, LCD_RW, 0);
	LCD_COMMAND(FUNCTION_SET);
	SysCtlDelay(SysCtlClockGet()/3000);
	LCD_COMMAND(DISPLAY_CONTROL);

	LCD_COMMAND(CLEAR_DISPLAY);
	SysCtlDelay(SysCtlClockGet()/1500);
	LCD_COMMAND(ENTRY_MODE);
	SysCtlDelay(SysCtlClockGet()/1500);

}




